export default [
    {
        key:'january',
        name:'January',
    }
    ,{
        key:'february',
        name:'February',
    },
    {
        key:'march',
        name:'March',
    },
    {
        key:'april',
        name:'April',
    },
    {
        key:'may',
        name:'May',
    },
    {
        key:'june',
        name:'June'
    },
    {
        key:'july',
        name:'July',
    },
    {
        key:'august',
        name:'August',
    },
    {
        key:'september',
        name:'September',
    },
    {
        key:'october',
        name:'October',
    },
    {
        key:'november',
        name:'November',
    },
    {
        key:'december',
        name:'December',
    }
];